sudo: required

services:
  - docker

script:
  - make build

after_success:
  - |
    if [[ "$TRAVIS_BRANCH" == "master" && "$TRAVIS_PULL_REQUEST" == "false" ]]; then
      docker log -u "$DOCKER_USERNAME" -p "$DOCKER_PASSWORD"
      make push
    fi
